name: CI
on:
  push:
    branches: [main]
  pull_request_target:
    branches: [main]

permissions:
  contents: read # for checkout repository
  actions: read # for fetching base branch bundle stats
  pull-requests: write # for comments

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "${{ github.event.pull_request.merge_commit_sha }}"
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - run: npm ci
      - run: npm run build
      - uses: exoego/esbuild-bundle-analyzer@main
        with:
          metafiles: "out/meta.json"
